
--DDL
CREATE DATABASE LocadoraDDL_Tarde;
USE LocadoraDDL_Tarde;

CREATE TABLE Empresa (
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (200)
);

CREATE TABLE Marca (
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (200)
);

CREATE TABLE Cliente (
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (200),
	CPF INT
);

CREATE TABLE Modelo (
	IdModelo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (200),
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca)
);

CREATE TABLE Veiculo (
	IdVeiculo INT PRIMARY KEY IDENTITY,
	Placa VARCHAR(200),
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo),
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa)
);

CREATE TABLE Aluguel (
	IdAluguel INT PRIMARY KEY IDENTITY,
	DataInicio DATE,
	DataFinal DATE,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo)
);

ALTER TABLE Cliente
ALTER COLUMN CPF VARCHAR(100);